### PR TITLE
Premature crash prevention: Remove tickwarp limit changing mixin

### PR DESCRIPTION
**Pull request by altrisi**
In recent commits, the tickwarp limit has been removed in Carpet itself.

That does not only make the mixin useless, but would also (probably, didn't really test it) make it crash when the next version is released, since the mixin target would no longer be valid.

This change won't be backported to previous versions, so those don't need changes. Only this and 1.17 does.

Updated the READMEs too, I _think_ I removed the correct line of `README_CN`.

### CODE REVIEW

**Comment by Fallen-Breath** [comment]
I'll prefer leave the mixin there and use a fail-proof injection than remove the mixin. It's more for version compatibility (1.16.2 ~ 1.16.4) since there are people playing on 1.16.2 for piglin doop and fabric-carpet itself proprably will only update the 1.16.4 version

For the doc part, it's ok if you modify the English doc only, I can handle the Chinese one later

**Comment by Fallen-Breath** [comment]
Done in 82eb5ce5899b14d5f4a7566af26756c642b16efd with backwards compatibility, thanks for reminding anyway

**Comment by altrisi** [comment]
Ok, makes sense. Since branch name said 1.16.4 thought it was only for 1.16.4+ (even though mc didn't change in 16.2-.4, didn't really think).

**Comment by Fallen-Breath** [comment]
Ye that might be confusing. btw if you look into the release page or fabric.mod.json you can found that it works for 1.16.2 to 1.16.4.

I have added a development section at the end of readme now to prevent these misleading thing from happening again

**Pull request closed without merging**
